import { useMemo, useState } from 'react'
import type { OrderSummary } from '../types/order.ts'
import type { GpcContainer } from '../lib/gpc/container.ts'
import { decodeOrderBlock, describeItem, planOrderBlock } from '../lib/gpc/orderBlock.ts'
import type { OrderBlockPlan } from '../lib/gpc/orderBlock.ts'
import { fieldChanges } from '../lib/gpc/applyOrderBlock.ts'
import './PasteOrderModal.css'

/**
 * Pasting a whole order in one go.
 *
 * The block comes from whatever system already holds the order — a sales order
 * in the ERP — so that nobody retypes an address or hand-picks forty SAP codes
 * out of a catalog with several thousand articles in it.
 *
 * Nothing is applied until the operator has seen what it would do. A block can
 * be wrong in ways only a person can judge: an article withdrawn since the
 * quote, a catalog that has moved on, a shipping address that should not be
 * overwritten. So the preview is the feature, not a courtesy.
 */
export function PasteOrderModal({
  order,
  pdb,
  openCatalog,
  onApply,
  onCancel,
}: {
  order: OrderSummary
  pdb: GpcContainer | null
  openCatalog: string
  onApply: (plan: OrderBlockPlan) => void
  onCancel: () => void
}) {
  const [text, setText] = useState('')

  const { plan, error } = useMemo(() => {
    if (!text.trim() || !pdb) return { plan: null, error: null }
    try {
      return { plan: planOrderBlock(decodeOrderBlock(text), pdb, openCatalog), error: null }
    } catch (err) {
      return { plan: null, error: err instanceof Error ? err.message : String(err) }
    }
  }, [text, pdb, openCatalog])

  const changes = useMemo(() => (plan ? fieldChanges(order, plan) : []), [order, plan])
  const unresolved = plan?.items.filter((i) => !i.resolved) ?? []
  const resolved = plan?.items.filter((i) => i.resolved) ?? []

  return (
    <div className="modal-overlay" onClick={e => { if (e.target === e.currentTarget) onCancel() }}>
      <div className="paste-order-modal" role="dialog" aria-modal="true" aria-label="Paste order">
        <h3 className="modal-title">Paste Order</h3>

        <label className="modal-label">
          Paste the block generated by your sales order
          <textarea
            className="paste-order-input"
            autoFocus
            spellCheck={false}
            value={text}
            onChange={e => setText(e.target.value)}
            placeholder={'-----BEGIN GPC ORDER-----\n…\n-----END GPC ORDER-----'}
          />
        </label>

        {error && <p className="paste-order-error">{error}</p>}

        {plan && (
          <div className="paste-order-preview">
            {plan.block.source && (
              <p className="paste-order-source">
                From {plan.block.source.system ?? 'another system'}
                {plan.block.source.ref ? ` · ${plan.block.source.ref}` : ''}
                {plan.block.source.generated ? ` · ${plan.block.source.generated.slice(0, 16).replace('T', ' ')}` : ''}
              </p>
            )}

            {plan.warnings.map((w, i) => (
              <p key={i} className="paste-order-warning">{w}</p>
            ))}

            {unresolved.length > 0 && (
              <section className="paste-order-section">
                <h4 className="paste-order-heading paste-order-heading--bad">
                  {unresolved.length} item{unresolved.length === 1 ? '' : 's'} could not be matched
                </h4>
                <ul className="paste-order-list">
                  {unresolved.map(entry => (
                    <li key={entry.index}>
                      <span className="paste-order-item">{describeItem(entry)}</span>
                      <span className="paste-order-problem">{entry.problem}</span>
                    </li>
                  ))}
                </ul>
                <p className="paste-order-hint">
                  These are left out. Everything else can still be applied.
                </p>
              </section>
            )}

            {resolved.length > 0 && (
              <section className="paste-order-section">
                <h4 className="paste-order-heading">{resolved.length} item{resolved.length === 1 ? '' : 's'} to add</h4>
                <ul className="paste-order-list">
                  {resolved.map(entry => (
                    <li key={entry.index}><span className="paste-order-item">{describeItem(entry)}</span></li>
                  ))}
                </ul>
              </section>
            )}

            {changes.length > 0 && (
              <section className="paste-order-section">
                <h4 className="paste-order-heading">{changes.length} field{changes.length === 1 ? '' : 's'} to change</h4>
                <ul className="paste-order-list paste-order-list--fields">
                  {changes.map((c, i) => <li key={i}>{c}</li>)}
                </ul>
              </section>
            )}

            {resolved.length === 0 && changes.length === 0 && (
              <p className="paste-order-hint">This block would change nothing.</p>
            )}
          </div>
        )}

        <div className="modal-actions">
          <button type="button" className="modal-btn modal-btn-cancel" onClick={onCancel}>Cancel</button>
          <button
            type="button"
            className="modal-btn modal-btn-add"
            disabled={!plan || (resolved.length === 0 && changes.length === 0)}
            onClick={() => plan && onApply(plan)}
          >
            {unresolved.length > 0 ? `Apply the other ${resolved.length + changes.length}` : 'Apply'}
          </button>
        </div>
      </div>
    </div>
  )
}
