/**
 * Generated by fidelity/harness/gen-member-order.mjs — do not edit by hand.
 *
 * The order .NET's XmlSerializer writes and reads each class's members in,
 * taken from the GPC assemblies' own declarations. An element out of this
 * order, or one naming no member, and GPC rejects the whole file with
 * "This file has no Order-Part".
 *
 * Names only. Regenerate from the decompiled sources when GPC changes.
 */

/** Element order within each class an order can contain. */
export const MEMBER_ORDER: Record<string, readonly string[]> = {
  AccountDetailsData: ['AccountNumber', 'VatId', 'City', 'CompanyName', 'CompanyNameTwo', 'CompanyType', 'Country', 'CustomerIdAtGom', 'Department', 'DepartmentTwo', 'Email', 'HpcPoBox', 'IsDistributor', 'IsNewCustomer', 'Phone', 'PhoneCountryCode', 'PhonePrefix', 'Reference', 'StateProvince', 'Street', 'StreetTwo', 'StreetThree', 'Website', 'ZipPostalCode'],
  Article: ['AbasNr', 'SapCharaterTraits', 'SapCharaterTraitValues', 'SapNr', 'ApplicableFee', 'ArticlePriceLists', 'Description', 'FilterTags', 'GroupLevel1', 'GroupLevel2', 'HideArticleInSummary', 'HidePrice', 'Hyperlink', 'IsHidden', 'Labels', 'LongName', 'PriceOnRequest', 'QuantityDiscounts', 'HasMaxQuantityDiscount', 'IsItemWideQuantityDiscount', 'Ranking', 'RegionalRestrictionNotInTheseCountriesRegions', 'ShortName', 'Unit', 'LinkedArticles', 'UserBlacklist', 'Unclean', 'IsSubconfiguration', 'MPG'],
  ArticlePriceList: ['Name', 'Currency', 'IsCustomerOrder', 'Dp', 'Msrp', 'EuroMsrp', 'CalculationTime', 'ExchangeRate', 'DestinationFactor', 'PriceOnRequest'],
  AttachedFile: ['FileName', 'Size', 'AttachedOn', 'HasToBeAdded'],
  ConfigurationItem: ['ApplicableFee', 'IsHidden', 'AsSubItemOnly', 'Flatten', 'UserBlacklist', 'RegionalRestrictionNotInTheseCountriesRegions', 'GroupLevel1', 'GroupLevel2', 'GroupLevel3', 'Name', 'Parameter', 'WorksheetArticleFilter', 'ItemType', 'AdditionalMandatoryFields', 'IsOppIdMandatory', 'Question1', 'Question2', 'Question3', 'Question1Formats', 'Question2Formats', 'Question3Formats', 'Question1Tooltip', 'Question2Tooltip', 'Question3Tooltip', 'SapNr', 'SapItemCategory', 'ProductionArticles', 'Discounts', 'Unclean'],
  ConfigurationItemData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden'],
  ConfigurationItemDataCalculation: ['OrderValueToGom', 'EndCustomerPrice', 'TotalMargin'],
  CountryAndIso: ['Country', 'CountryCode', 'ExportControl', 'Iso', 'PriceFactor'],
  Currency: ['Iso', 'Display', 'Description', 'ExchangeRate', 'ValidFrom'],
  DependentListScreenData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden', 'Sections', 'SubConfigurations', 'CustomArticlesQuantityDiscount'],
  DependentListSupportScreenData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden', 'Sections', 'SubConfigurations', 'CustomArticlesQuantityDiscount', 'StartNewContract', 'EndNewContract', 'EndOldContract', 'IsOlderSelected', 'DongleId', 'YearBasedDiscount', 'CustomYearBasedDiscount'],
  EconomyYearData: ['StartDate', 'EndDate', 'Wsj', 'Months', 'MonthsSinceStart', 'Value'],
  FreeArticle: ['Amount', 'Step', 'Article', 'OverwrittenDp', 'OverwrittenMrsp', 'PriceOnRequest', 'EuroMsrp', 'Msrp', 'Dp', 'SumMsrp', 'SumDp', 'CustomQuantityDiscount', 'AbasNr', 'SapNr'],
  FreeArticlesScreenData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden', 'FreeArticles'],
  FreeListArticle: ['Amount', 'Step', 'Article', 'OverwrittenDp', 'OverwrittenMrsp', 'PriceOnRequest', 'EuroMsrp', 'Msrp', 'Dp', 'SumMsrp', 'SumDp', 'CustomQuantityDiscount', 'AbasNr', 'SapNr'],
  FreeListScreenData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden', 'FreeListArticles'],
  LocalTechnicalContact: ['AcademicDegree', 'AdditionalEmail', 'AdditionalPhone', 'AdditionalPhoneCountryCode', 'AdditionalPhonePrefix', 'BusinessPhone', 'BusinessPhoneCountryCode', 'BusinessPhonePrefix', 'Department', 'Email', 'FirstName', 'Gender', 'IsOtherDepartment', 'IsOtherPosition', 'IsOtherSource', 'LastName', 'MobilePhone', 'MobilePhoneCountryCode', 'MobilePhonePrefix', 'Position', 'Source', 'Title'],
  OrderAdministration: ['InvoiceAccountNumber', 'InvoiceAddressType', 'InvoiceCity', 'InvoiceCompanyName', 'InvoiceCompanyNameTwo', 'InvoiceCountry', 'InvoiceDepartment', 'InvoiceDepartmentTwo', 'InvoiceHPCPOBox', 'InvoiceNewCustomer', 'InvoiceState', 'InvoiceStreet', 'InvoiceStreetTwo', 'InvoiceStreetThree', 'InvoiceZIP', 'InvoicePaymentTerm', 'IsTarifNumberToggler', 'ShippingAccountNumber', 'ShippingAddressType', 'ShippingCity', 'ShippingCompanyName', 'ShippingCompanyNameTwo', 'ShippingContactPerson', 'ShippingCountry', 'ShippingDepartment', 'ShippingDepartmentTwo', 'ShippingHPCPOBox', 'ShippingMethod', 'ShippingNewCustomer', 'ShippingState', 'ShippingStreet', 'ShippingStreetTwo', 'ShippingStreetThree', 'ShippingZIP', 'ShippingFreightTerm', 'SpecialShippingInstructions'],
  OrderData: ['DependentListsData', 'FreeArticlesData', 'FreeListArticlesData', 'SupportArticlesData', 'AccountDetailsData', 'AttachedFiles', 'CaseId', 'CleanOrder', 'ReasonUnclean', 'Comment', 'CreationDate', 'Destination', 'DestinationNew', 'DiscountForCustomer', 'DiscountSplitPercentShare', 'DiscountSplitCurrencyShare', 'Distributor', 'Duration', 'EndDate', 'OrderUsedInWeaponProduction', 'FinalPriceForEndCustomer', 'FinalPriceForEndCustomerLocalCurrency', 'FinalPriceForEndCustomerWithHandlingFee', 'GomCurrency', 'Currency', 'DifferentLocalCurrencyIso', 'HandlingFee', 'HandlingFeeName', 'HasPriceOnRequest', 'HOMCenter', 'IsCustomerDiscountAcknowledged', 'DifferentFinalPriceForEndCustomerChecked', 'DirectSalesChecked', 'IsHandlingFeeApplicable', 'ContractType', 'LastModified', 'LocalTechnicalContact', 'Msrp', 'Dp', 'OrderAdministration', 'OrderDate', 'OrderGuid', 'OrderNumber', 'OrderStatus', 'OrderValueToGom', 'OrderValueToGomWithHandlingFee', 'OpportunityID', 'GomOrderNumber', 'PriceList', 'SaleInformations', 'SourceFileName', 'Username', 'FinalizeUsername', 'FinalizedDateTime'],
  OrderedDiscount: ['Position', 'Discount'],
  QuantityDiscount: ['TriggerAmount', 'Discount'],
  SaleInformations: ['ClassificationProperty', 'CompetitionInformations', 'DemoAndBenchmark', 'InvestmentType', 'IsOtherPartSize', 'Pricing', 'ReasonsToWin', 'SaleCycle'],
  SectionArticleScreenData: ['Amount', 'Step', 'Article', 'OverwrittenDp', 'OverwrittenMrsp', 'PriceOnRequest', 'EuroMsrp', 'Msrp', 'Dp', 'SumMsrp', 'SumDp', 'CustomQuantityDiscount', 'Name', 'AdditionalArticleName', 'AmountMode', 'WasSetByUser', 'ManualInputWasReset'],
  SectionScreenData: ['Name', 'SectionArticles', 'SapCharacterTraitNames', 'Comments'],
  SoftwareSupportArticleCalculationData: ['SapUpgradeNr', 'ReEntryFee', 'VolumeDiscount', 'YearDiscount', 'MsrpNewContract', 'SumMsrp', 'SumDp', 'DiscountedMsrp', 'DiscountedDp', 'DiscountedDpWithSplitFactor', 'MissingMonths', 'NewMonths'],
  SupportArticle: ['Amount', 'Step', 'Article', 'OverwrittenDp', 'OverwrittenMrsp', 'PriceOnRequest', 'EuroMsrp', 'Msrp', 'Dp', 'SumMsrp', 'SumDp', 'CustomQuantityDiscount', 'EconomyYears', 'SoftwareSupportArticleCalculationData', 'EndNewContract', 'EndOldContract', 'IsOlderSelected', 'MsrpForMissingMonth', 'MsrpForNewContract', 'MsrpPerYear', 'SensorSnDongleId', 'StartNewContract'],
  SupportScreenData: ['ConfigurationItemDataCalculation', 'Comments', 'ConfigurationItem', 'UseInCalculation', 'HasPriceOnReqeust', 'No', 'Reply1', 'Reply2', 'Reply3', 'TotalDp', 'TotalMsrp', 'Discount', 'IsDiscountPercentage', 'IsHidden', 'HardwareSupportArticles', 'SoftwareSupportArticles', 'IsLegacy', 'DependentListSupportScreenDatas', 'CustomVolumeDiscount', 'VolumeDiscount'],
}

/**
 * Which class each element belongs to, by its parent class. A `[]` prefix marks
 * a list: the element is a wrapper whose children are each named after the type.
 */
export const CHILD_CLASS: Record<string, Record<string, string>> = {
  Article: { ArticlePriceLists: '[]ArticlePriceList', QuantityDiscounts: '[]QuantityDiscount' },
  ConfigurationItem: { ProductionArticles: '[]Article', Discounts: '[]OrderedDiscount' },
  ConfigurationItemData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem' },
  DependentListScreenData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem', Sections: '[]SectionScreenData', SubConfigurations: '[]ConfigurationItemData' },
  DependentListSupportScreenData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem', Sections: '[]SectionScreenData', SubConfigurations: '[]ConfigurationItemData' },
  FreeArticle: { Article: 'Article' },
  FreeArticlesScreenData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem', FreeArticles: '[]FreeArticle' },
  FreeListArticle: { Article: 'Article' },
  FreeListScreenData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem', FreeListArticles: '[]FreeListArticle' },
  OrderData: { DependentListsData: '[]DependentListScreenData', FreeArticlesData: '[]FreeArticlesScreenData', FreeListArticlesData: '[]FreeListScreenData', SupportArticlesData: '[]SupportScreenData', AccountDetailsData: 'AccountDetailsData', AttachedFiles: '[]AttachedFile', DestinationNew: 'CountryAndIso', Currency: 'Currency', LocalTechnicalContact: 'LocalTechnicalContact', OrderAdministration: 'OrderAdministration', SaleInformations: 'SaleInformations' },
  SectionArticleScreenData: { Article: 'Article' },
  SectionScreenData: { SectionArticles: '[]SectionArticleScreenData' },
  SupportArticle: { Article: 'Article', EconomyYears: '[]EconomyYearData', SoftwareSupportArticleCalculationData: 'SoftwareSupportArticleCalculationData' },
  SupportScreenData: { ConfigurationItemDataCalculation: 'ConfigurationItemDataCalculation', ConfigurationItem: 'ConfigurationItem', HardwareSupportArticles: '[]SupportArticle', SoftwareSupportArticles: '[]SupportArticle', DependentListSupportScreenDatas: '[]DependentListSupportScreenData' },
}

/**
 * Values each enum-typed element accepts, keyed `Class.Element`.
 *
 * XmlSerializer writes an enum as its member *name*. A display label — "GOM
 * Partner" where the enum says `GOMPartner` — is an "Instance validation
 * error" and the whole document fails to deserialize.
 */
export const ENUM_VALUES: Record<string, readonly string[]> = {
  'OrderData.ContractType': ['Loan', 'Purchase', 'Rent'],
  'OrderData.OrderStatus': ['Editing', 'Finalized'],
  'OrderAdministration.InvoiceAddressType': ['Customer', 'GOMPartner', 'HomCenter', 'Other'],
  'OrderAdministration.ShippingAddressType': ['Customer', 'GOMPartner', 'HomCenter', 'Other'],
  'ConfigurationItem.ItemType': ['DependentList', 'FreeList', 'Supportextension', 'DongleList', 'FreeArticles', 'DiscountArticles'],
  'SectionArticleScreenData.AmountMode': ['Implication', 'SectionSpecialFunction', 'UserChoice', 'SoftImplication', 'Default', 'Reset', 'None'],
}

/** The order members of `className` must be written in, or null if unknown. */
export function memberOrder(className: string): readonly string[] | null {
  return MEMBER_ORDER[className] ?? null
}
